#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F398DEAE440091C (infra-root@openstack.org)
#
Name     : oslo.middleware
Version  : 4.0.1
Release  : 67
URL      : https://tarballs.openstack.org/oslo.middleware/oslo.middleware-4.0.1.tar.gz
Source0  : https://tarballs.openstack.org/oslo.middleware/oslo.middleware-4.0.1.tar.gz
Source1  : https://tarballs.openstack.org/oslo.middleware/oslo.middleware-4.0.1.tar.gz.asc
Summary  : Oslo Middleware library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.middleware-license = %{version}-%{release}
Requires: oslo.middleware-python = %{version}-%{release}
Requires: oslo.middleware-python3 = %{version}-%{release}
Requires: Jinja2
Requires: WebOb
Requires: debtcollector
Requires: oslo.config
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: six
Requires: statsd
Requires: stevedore
BuildRequires : Jinja2
BuildRequires : WebOb
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : oslo.config
BuildRequires : oslo.context
BuildRequires : oslo.i18n
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : six
BuildRequires : statsd
BuildRequires : stevedore

%description
===============
oslo.middleware
===============
.. image:: https://img.shields.io/pypi/v/oslo.middleware.svg
:target: https://pypi.org/project/oslo.middleware/
:alt: Latest Version

%package license
Summary: license components for the oslo.middleware package.
Group: Default

%description license
license components for the oslo.middleware package.


%package python
Summary: python components for the oslo.middleware package.
Group: Default
Requires: oslo.middleware-python3 = %{version}-%{release}

%description python
python components for the oslo.middleware package.


%package python3
Summary: python3 components for the oslo.middleware package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.middleware package.


%prep
%setup -q -n oslo.middleware-4.0.1
cd %{_builddir}/oslo.middleware-4.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582741359
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.middleware
cp %{_builddir}/oslo.middleware-4.0.1/LICENSE %{buildroot}/usr/share/package-licenses/oslo.middleware/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.middleware/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
