#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEB6CCA1483FA74EC (infra-root@openstack.org)
#
Name     : oslo.middleware
Version  : 3.26.0
Release  : 50
URL      : https://tarballs.openstack.org/oslo.middleware/oslo.middleware-3.26.0.tar.gz
Source0  : https://tarballs.openstack.org/oslo.middleware/oslo.middleware-3.26.0.tar.gz
Source99 : https://tarballs.openstack.org/oslo.middleware/oslo.middleware-3.26.0.tar.gz.asc
Summary  : Oslo Middleware library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.middleware-python
Requires: Jinja2
Requires: WebOb
Requires: debtcollector
Requires: oslo.config
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: six
Requires: stevedore
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===================================
oslo.middleware
===================================

%package python
Summary: python components for the oslo.middleware package.
Group: Default

%description python
python components for the oslo.middleware package.


%prep
%setup -q -n oslo.middleware-3.26.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492528279
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492528279
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
