#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.middleware
Version  : 3.8.0
Release  : 35
URL      : http://tarballs.openstack.org/oslo.middleware/oslo.middleware-3.8.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.middleware/oslo.middleware-3.8.0.tar.gz
Summary  : Oslo Middleware library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.middleware-python
BuildRequires : Jinja2
BuildRequires : Sphinx-python
BuildRequires : WebOb-python
BuildRequires : coverage-python
BuildRequires : debtcollector-python
BuildRequires : docutils
BuildRequires : hacking
BuildRequires : iso8601-python
BuildRequires : netaddr
BuildRequires : netifaces-python
BuildRequires : oslo.config
BuildRequires : oslo.context-python
BuildRequires : oslo.utils-python
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : stevedore
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv

%description
===================================
oslo.middleware
===================================

%package python
Summary: python components for the oslo.middleware package.
Group: Default
Requires: Jinja2
Requires: WebOb-python
Requires: debtcollector-python
Requires: oslo.config
Requires: oslo.context-python
Requires: oslo.utils-python
Requires: stevedore

%description python
python components for the oslo.middleware package.


%prep
%setup -q -n oslo.middleware-3.8.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
